### ISSUE TITLE
fork/exec /bin/sh: operation not permitted

### ISSUE THREAD

**Issue by 724686158** [xianlubird/mydocker#1]
2.1.2 UTS Namespace
in elementary os 0.41(ubuntu 16.04, Linux version 4.8.0-58-generic)

solitarius@Lain:~/GoglandProjects/DockerTry$ go run UTS_NAMESPACE.go 
2017/07/11 10:10:47 fork/exec /bin/sh: operation not permitted

**Comment by xianlubird** [comment]
operation not permitted.   Root 权限开了没

**Comment by BSWANG** [comment]
应该是solitarius这个用户没有fork/exec的权限，建议切换成root运行。我先关闭这个issue，后续有疑问可以随时再反馈。

**Comment by 724686158** [comment]
好，我会测试一下。谢谢
