### ISSUE TITLE
build again err

### ISSUE THREAD

**Issue by timchenxiaoyu** [xianlubird/mydocker#10]
go build
go build github.com/xianlubird/mydocker/vendor/github.com/urfave/cli: /usr/local/go/pkg/tool/linux_amd64/compile: open /dev/null: no such file or directory
go build github.com/xianlubird/mydocker/vendor/github.com/vishvananda/netns: /usr/local/go/pkg/tool/linux_amd64/compile: open /dev/null: no such file or directory
go build github.com/xianlubird/mydocker/vendor/github.com/Sirupsen/logrus: /usr/local/go/pkg/tool/linux_amd64/compile: open /dev/null: no such file or directory
go build github.com/xianlubird/mydocker/cgroups/subsystems: /usr/local/go/pkg/tool/linux_amd64/compile: open /dev/null: no such file or directory
go build github.com/xianlubird/mydocker/nsenter: /usr/local/go/pkg/tool/linux_amd64/cgo: open /dev/null: no such file or directory

**Comment by BSWANG** [comment]
看报错是没有/dev/null，请确认下是否是在Linux系统下编译的？

**Comment by timchenxiaoyu** [comment]
centos7.2   内核3.10。重启后，第一次不行，多次编译后会出现

**Comment by BSWANG** [comment]
原因应该跟你另外提的一个issue相关，由于centos中/dev/文件系统未重新挂载导致的，mknod 命令创建出/dev/null或许有用，建议使用书中要求的操作系统和内核。
