### ISSUE TITLE
 no such file or directory

### ISSUE THREAD

**Issue by timchenxiaoyu** [xianlubird/mydocker#11]
./mydocker run -ti busybox sh
{"level":"info","msg":"createTty true","time":"2017-08-23T14:10:44+08:00"}
{"level":"error","msg":"get init process error readlink /proc/self/exe: no such file or directory","time":"2017-08-23T14:10:44+08:00"}
{"level":"error","msg":"New parent process error","time":"2017-08-23T14:10:44+08:00"}

after mount -t proc proc /proc

ok

**Comment by BSWANG** [comment]
请问你的操作系统版本和内核版本？我们建议的版本是在ubuntu + kernel 3.13

**Comment by timchenxiaoyu** [comment]
centos7.2  内核3.10

**Comment by BSWANG** [comment]
建议使用Ubuntu 14.04和3.13内核，对于centos 7的兼容性当时没有考虑，你可以考察一下，欢迎提交PR。

**Comment by boynanboy** [comment]
> centos7.2 内核3.10

hi 这个问题你解决了吗，我也是相同环境，这个问题解决不了，绕不过去
