### ISSUE TITLE
书买了，看到第三章，咋说呢。。。

### ISSUE THREAD

**Issue by zalemwoo** [xianlubird/mydocker#2]
https://github.com/xianlubird/mydocker/blob/code-3.2/container/init.go#L14-L32

line 16: if cmdArray == nil || len(cmdArray) == 0 既然cmdArray是切片类型，nil值的len也是0前一半没必要吧
line 20: setUpMount()  为什么不是 setupMount() setUp？
line 24: log.Errorf("Exec loop path error %v", err)    loop? look吧？
line 27: log.Infof("Find path %s", path)   Find? Found吧？
line 28: cmdArray[0:]? 切片类型从0开始取新切片的目的是啥？ 和cmdArray有啥区别？

**Comment by xianlubird** [comment]
多谢指正，写书期间时间紧张，有些代码细节没有处理好，欢迎 PR 指正。

**Comment by zalemwoo** [comment]
subsystem包里面，Subsystem和SubSystem的命名没有统一，几个XXXSubSystem里面的Remove()和Apply()方法除了s.Name()不同没有不同，也可以用helper方法包一下。SubsystemsIns的命名也很奇怪。。。
另外，第四章里面引导读者以root用户身份操作感觉也不合适，busybox，挂载点那些，在普通用户的home下面就好了，需要特权用户的时候再sudo吧，几乎只有run的时候才需要。能不碰root，就不碰root。

书很不错，浅显易懂，循序渐进，操作性强，正一行一行对着码，获益匪浅，非常感谢。

希望下一版能精益求精，更加精彩～
