### ISSUE TITLE
I can't found mysql account

### ISSUE THREAD

**Issue by shihp** [xianlubird/mydocker#20]
I am a new user, and when i print 
`echo $(docker logs wordpress-test | grep password)`

can't find mysql account 

just have this 

> Complete! WordPress has been successfully copied to /var/www/html
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Thu Jan 04 06:30:23.474586 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.0 configured -- resuming normal operations
[Thu Jan 04 06:30:23.474760 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

**Comment by xianlubird** [comment]
你可以去看看你用的wordpress 版本对应的docker hub 的介绍
