### ISSUE TITLE
seems wrong with network.Bridge initializer

### ISSUE THREAD

**Issue by s3341458** [xianlubird/mydocker#26]
I just record issue I found, after I got through all of this book, I will submit pr for it.

seems the struct initializer in code-6.5 are wrong.
in branch code-6.5 network/bridge.go
br := &netlink.Bridge{la}
addr := &netlink.Addr{ipNet}
will cause "too few values in struct initializer"

**Comment by BSWANG** [comment]
Cause of go netlink library modify the struct field. PR is welcome.
