### ISSUE TITLE
seems wrong with "user namespace"

### ISSUE THREAD

**Issue by wbtlb** [xianlubird/mydocker#28]
i just test "user namespaces", and i found after run my code, it will exit status 1

**Comment by BSWANG** [comment]
Refer #13 

> 4.2+的内核中userns的使用方式变化导致operation not permitted
    Centos 7.x中的内核不支持userns

**Comment by wbtlb** [comment]
我的内核版本是3.10的，也会有这种问题吗？

**Comment by BSWANG** [comment]
@wbtlb 3.10还不支持userns

**Comment by wbtlb** [comment]
但我看您的文档上面写userns 内核版本不是从3.8就开始支持了？

**Comment by BSWANG** [comment]
@wbtlb 我说的不够标准，特性是在3.8中加进去的，很多发行版的3.10的内核（特别是centos/redhat）并没有把它编译到内核中，所以不支持。

**Comment by BSWANG** [comment]
建议使用我们建议的ubuntu 14.04 + 3.13的内核测试。

**Comment by wbtlb** [comment]
好的，感谢您的解答。

**Comment by wbtlb** [comment]
另外，那在内核3.10中，docker是如何实现userns的呢？

**Comment by BSWANG** [comment]
@wbtlb docker默认是不会创建userns的，只有指定了user-mapping才会做userns，在那个时候会判断是否能支持，不支持就直接报错了。

**Comment by wbtlb** [comment]
学习了，再次感谢。
