### ISSUE TITLE
Got {"level":"error","msg":"fork/exec /proc/self/exe: no such file or directory","time":"2018-04-25T23:19:48-04:00"}

### ISSUE THREAD

**Issue by vincent-pli** [xianlubird/mydocker#33]
I got error:
{"level":"error","msg":"fork/exec /proc/self/exe: no such file or directory","time":"2018-04-25T23:19:48-04:00"}
when I try ./mydocker run -ti /bin/ls
after run command ./mydocker run -ti /bin/ls success.

fix by run "mount -t proc proc /proc"

Could anybody tell me what happen, many thanks

**Comment by s3341458** [comment]
@vincent-pli 
我来尝试回答你这个问题, 因为我是用archilinux 根据这个书上的code， 一步步重作了这个project。

我在
pivotRoot(pwd) 前加了:
// enable the mount namespace works properly on my archlinux computer
syscall.Mount("", "/", "", syscall.MS_PRIVATE|syscall.MS_REC, "")

我当时的笔记是
Using syscall.Mount("", "/", "", syscall.MS_PRIVATE|syscall.MS_REC, "") makes the mount namespace works properly on my archlinux computer, systemd made "/" mounted as shared by default.

我的印象是systemd 加入linux之后, mount namespace 就变成 shared by default, 所以你必须显示
声明你要这个新的mount namespace独立。

有兴趣可以看看我的fork version, https://github.com/s3341458/mydocker， 希望可以帮到你们

最近在找工作，求打星， 拜谢！！ pray

**Comment by wadeling** [comment]
我也碰到相同的问题，我的环境是14.04.4，kernal 3.13

**Comment by liusmycroft** [comment]
菜鸡的理解：

```
// 第一个参数是指proc信息，是虚的，在内存中存在，是内核提供的关于内核运行状态的一系列特殊文件
// 下面这行代码的意思是将proc信息"挂载"到/proc文件夹中
syscall.Mount("proc", "/proc", "proc", uintptr(defaultMountFlags), "")
```
当程序跑到这一行时proc代表的是./mydocker这个程序的proc信息，跑完这行以后./mydocker的内核运行信息就被挂在到/proc文件夹中，而当退出./mydocker时由于像楼上所说是shared的，所以退出来后的/proc目录的内容依旧是运行./mydocker时的内核信息之类的，而此时./mydocker已经退出了，没有pid，自然在/proc目录下也就没有self了
而再次运行mount -t proc proc /proc代表将当前进程（tty）的内核运行信息再次挂载到/proc上，相当于恢复操作，所以可以再跑一次./mydocker
