### ISSUE TITLE
实验环境问题

### ISSUE THREAD

**Issue by milkfr** [xianlubird/mydocker#34]
目前看到第三章

有一些问题

1、比如`mount -t proc proc /proc`命令执行后，书中没有恢复挂载的命令，会导致3-1的程序执行得到`fork/exec /proc/self/exe: no such file or directory`的错误，因为/proc的内容变了，/proc/self/exe文件没有了，看书的人一般应该都不熟这些环境变化的命令，希望每个实验做完有说明恢复环境的方法，毕竟拿自己的机器实验不知道怎么恢复比较惨，此外其他的挂载之类的实验也没有说明

2、2.2里限制内存后`stress`命令无法执行，比如显示100M则命令无法使用200M做参数无法启动，只能使用100M以下的参数，不知道是`stress`命令版本高了还是Ubuntu版本高了（我用16.04），希望能提供含有无问题完成所有实验的虚拟机环境（有所有软件和包）下载？

目前看书实验做下来感觉还好，环境问题还能自己鼓捣鼓捣解决，书写得很好，感觉做应用不懂一些依赖系统接口原理的我增长不少知识，当然最好比如aufs这些系统实现的算法原理书里也有提就更好了，看完再过来提建议

**Comment by yin32167** [comment]
遇到同样的问题

**Comment by BSWANG** [comment]
我们在写书的时候使用的是`ubuntu 14.04 + 3.13`的内核做的验证，这个应该在书中以及这个项目的置顶的issue中都有提及，使用其他的操作系统没有做兼容性的测试，你提问的问题应该可以在这个issue中找到答案 #13 

所以我先关闭掉这个issue了，继续在下面回复也是没关系的~

**Comment by s3341458** [comment]
我来尝试回答这个问题, 因为我是用archilinux 根据这个书上的code， 一步步重作了这个project。

我在
pivotRoot(pwd) 前加了:
// enable the mount namespace works properly on my archlinux computer
syscall.Mount("", "/", "", syscall.MS_PRIVATE|syscall.MS_REC, "")

我当时的笔记是
Using syscall.Mount("", "/", "", syscall.MS_PRIVATE|syscall.MS_REC, "") makes the mount namespace works properly on my archlinux computer, systemd made "/" mounted as shared by default.

我的印象是systemd 加入linux之后, mount namespace 就变成 shared by default, 所以你必须显示
声明你要这个新的mount namespace独立。

有兴趣可以看看我的fork version, https://github.com/s3341458/mydocker， 希望可以帮到你们

最近在找工作，求打星， 拜谢！！ :pray:

**Comment by liusmycroft** [comment]
菜鸡的理解：
```
// 第一个参数是指proc信息，是虚的，在内存中存在，是内核提供的关于内核运行状态的一系列特殊文件
// 下面这行代码的意思是将proc信息"挂载"到/proc文件夹中
syscall.Mount("proc", "/proc", "proc", uintptr(defaultMountFlags), "")
```
当程序跑到这一行时proc代表的是./mydocker这个程序的proc信息，跑完这行以后./mydocker的内核运行信息就被挂在到/proc文件夹中，而当退出./mydocker时由于像楼上所说是shared的，所以退出来后的/proc目录的内容依旧是运行./mydocker时的内核信息之类的，而此时./mydocker已经退出了，没有pid，自然在/proc目录下也就没有self了
而再次运行mount -t proc proc /proc代表将当前进程（tty）的内核运行信息再次挂载到/proc上，相当于恢复操作，所以可以再跑一次./mydocker
