### ISSUE TITLE
code-3.2编译时出现错误

### ISSUE THREAD

**Issue by yanghx9013** [xianlubird/mydocker#35]
$ git checkout code-3.2
$ go build .
出现错误：
./main_command.go:58: not enough arguments in call to container.RunContainerInitProcess
./run.go:14: not enough arguments in call to container.NewParentProcess
./run.go:14: assignment count mismatch: 2 = 1

运行环境：ubuntu16.04 
go version：1.6.2

请教~

**Comment by BSWANG** [comment]
应该是go的版本太老了，建议升级到1.7.x以上版本，我本地测试是没问题的：
```
➜  mydocker git:(b500ded)  git checkout code-3.2
HEAD is now at b500ded... fix bugs
➜  mydocker git:(b500ded)  go build .
➜  mydocker git:(b500ded) 
```

**Comment by machao23** [comment]
> @yanghx9013 应该是go的版本太老了，建议升级到1.7.x以上版本，我本地测试是没问题的：
> 
> ```
> ➜  mydocker git:(b500ded)  git checkout code-3.2
> HEAD is now at b500ded... fix bugs
> ➜  mydocker git:(b500ded)  go build .
> ➜  mydocker git:(b500ded) 
> ```

和环境变量有关系吗？我的是1.12.1，也有这问题
