### ISSUE TITLE
tag 3.2代码运行有问题

### ISSUE THREAD

**Issue by ResolveWang** [xianlubird/mydocker#40]
作者好，我在阅读本书3.2小节，动手做关于本节的实验时，遇到了一些问题，望解答

在提issue之前，我也翻了相关的issue，比如[#35](https://github.com/xianlubird/mydocker/issues/35)，[#6](https://github.com/xianlubird/mydocker/issues/6)，也想过通过自己解决，但是我go语言基本没怎么学习过，尝试了很久后问题仍然没解决，所以才提的这个issue，望作者能进行详细解答

我的操作系统是使用vagrant起的`ubuntu14.04`，vagrant box镜像是`bento/ubuntu-14.04`，具体实验环境如下
> uname -r 
3.13.0-135-generic
go version
go1.7.1 linux/amd64

我的操作及遇到的问题
> git clone https://github.com/xianlubird/mydocker.git
cd mydocker
git checkout code-3.2    #HEAD is now at b500ded... fix bugs        看commit信息是fix bug之后的
go build .

抛出的错误是
>./run.go:14: not enough arguments in call to container.NewParentProcess

这个错误相关issue可见[#35](https://github.com/xianlubird/mydocker/issues/35)，但是我的go版本本来就是`1.7.1`了，后来我又升级到`1.9.2`之后，还是有这个问题
>./run.go:14:49: not enough arguments in call to container.NewParentProcess
	have (bool)
	want (bool, string, string, string, []string)

然后我阅读了`tag-3.2`的代码，看到引用的包都是
> "github.com/xianlubird/mydocker/xxx"

之类的路径。

我的做法是将报错的那个包路径改成本地包引用
> "github.com/xianlubird/mydocker/container"   ->   	"./container"

然后`go build .`就没问题了，但是执行
> ./mydocker run -ti -m 100m stress --vm-bytes 200m --vm-keep -m 1

报错了
```
Incorrect Usage: flag provided but not defined: -vm-bytes

NAME:
   mydocker run - Create a container with namespace and cgroups limit
      mydocker run -ti [command]

USAGE:
   mydocker run [command options] [arguments...]

OPTIONS:
   --ti              enable tty
   -m value          memory limit
   --cpushare value  cpushare limit
   --cpuset value    cpuset limit

{"level":"fatal","msg":"flag provided but not defined: -vm-bytes","time":"2018-08-24T02:02:17Z"}
```

希望作者能复现一下这个问题，帮忙解决一下，感谢

**Comment by BSWANG** [comment]
包路径的问题，这个是go语言的标准的实践，需要把对应项目放到gopath的对应路径中，你需要在$GOPATH/src/github.com/xianlubird/mydocker/目录下开发就不会有问题。

**Comment by weikeit** [comment]
应该是`mydocker`把`stress`的参数`-vm-bytes`当成自己的参数解析了，在`stress`命令前面加上`--`即可终止`mydocker`对后面参数的解析：`./mydocker run -ti -m 100m -- stress --vm-bytes 200m --vm-keep -m 1`
