### ISSUE TITLE
write tasks happend  no space left on device

### ISSUE THREAD

**Issue by pibigstar** [xianlubird/mydocker#66]
![image](https://user-images.githubusercontent.com/33958530/73513267-dff4d800-4427-11ea-835d-5a296e58b2a6.png)

 write tasks have a err:  no space left on device, but  I have plenty of disk space, how can I fix it?

![image](https://user-images.githubusercontent.com/33958530/73513360-234f4680-4428-11ea-90f4-a6f30ecd07e3.png)

**Comment by srstack** [comment]
When using cpuset in NUMA architecture, cpuset.cpus and cpuset.mems need to
be written at the same time or both are empty to write PID to tas

派大星 <notifications@github.com> 于2020年1月31日周五 下午12:50写道：

**Comment by pibigstar** [comment]
Thank you for answering, it's work！
