### ISSUE TITLE
operation not permitted

### ISSUE THREAD

**Issue by kasheemlew** [xianlubird/mydocker#7]
2.1.6 User Namespace 第17页以root运行时报错：

    fork/exec /bin/sh: operation not permitted.

但是将`cmd.SysProcAttr.Credential = &syscall.Credential{Did: uint32(1), Gid: uint32(1) }`删掉后可以正常运行。

版本： Ubuntu 14.04  kernel: 4.4.0-31-generic

**Comment by BSWANG** [comment]
Duplicate to  #3

**Comment by kasheemlew** [comment]
请问能不能简单告诉我下这是什么原因。？

**Comment by kasheemlew** [comment]
@BSWANG

**Comment by BSWANG** [comment]
Linux kernel在3.19以上的版本中对user namespace做了些修改，链接是：https://go-review.googlesource.com/c/10670/
具体的解释 #3 中有说明
