### ISSUE TITLE
code-3.1运行后/proc/self被修改

### ISSUE THREAD

**Issue by kasheemlew** [xianlubird/mydocker#8]
code-3.1运行`./mydocker run -ti ./bin/sh`
之前

<img width="847" alt="screen shot 2017-08-22 at 14 01 48" src="https://user-images.githubusercontent.com/14333766/29550859-a204d58a-8742-11e7-8194-5b2f37266fda.png">

运行之后

<img width="693" alt="screen shot 2017-08-22 at 14 02 42" src="https://user-images.githubusercontent.com/14333766/29550861-a283eda2-8742-11e7-838e-ba67e29c5993.png">

<img width="603" alt="screen shot 2017-08-22 at 14 04 13" src="https://user-images.githubusercontent.com/14333766/29550896-cf04fe0c-8742-11e7-8dd2-14fdcfe66be6.png">

然后要重启才能恢复正常。

求解答。感谢！

**Comment by iarwen** [comment]
Because you have gone into a new namespace after run ` ./mydocker run -ti ./bin/sh`，type `exit` will back to your host`s namespace.

**Comment by kasheemlew** [comment]
已经执行过`exit`了。再`exit`就退出终端了。。

**Comment by kasheemlew** [comment]
已经执行过`exit`了，再`exit`就退出终端了 @iarwen

**Comment by iarwen** [comment]
`# sudo mount -t proc proc /proc`   have a try~

**Comment by kasheemlew** [comment]
解决了。谢谢。

**Comment by liuliqiang** [comment]
@iarwen  @xianlubird  

Is there better way to fixed this question?

I should use `mount -t proc proc /proc` every time after try to run `mydocker run` command, i don't think it's a good idea.
