### ISSUE TITLE
6.3.3一节中，是否存在未考虑边界情况的问题？

### ISSUE THREAD

**Issue by ruiwala** [xianlubird/mydocker#88]
6.3.1中举的例子是192.168.0.0/24，索引是0-254，分配的地址是192.168.0.1-192.168.0.255。
但6.3.3中初始化位图数组用的是strings.Rpeat("0",1<<unit8(size-one))，即2^8=256个0，索引变成了0-255。
当索引c=255的时候，是不是有点问题，ip[3]+=1就变成192.168.0.256了？

**Comment by BSWANG** [comment]
@ruiwala 好像确实有这个问题，另外网段最后一个地址，例如255也是不能使用的，可以提个PR将生成后将最后的两位置为1
